#!/bin/bash
VERSION=1.0.1

rm make_download make_build make_prepare
mkdir tmp

for lang in en en_AU en_GB en_NZ es fr it ja ru sv; do
for fmt in alaw g722 g729 gsm sln16 ulaw wav siren7 siren14; do
echo "${lang} ${fmt}"
if [ ! -f tmp/asterisk-core-sounds-${lang}-${fmt}-current.tar.gz ];then wget -P tmp https://downloads.asterisk.org/pub/telephony/sounds/asterisk-core-sounds-${lang}-${fmt}-current.tar.gz;fi
suma=$(sha256sum tmp/asterisk-core-sounds-${lang}-${fmt}-current.tar.gz | cut -d" " -f1)
cat <<EOF >>  make_download
ifneq (\$(CONFIG_PACKAGE_asterisk-core-sounds-${lang}-${fmt}-digium)\$(CONFIG_PACKAGE_asterisk-core-sounds-voicemail-${lang}-${fmt}-digium),)
\$(eval \$(call Download,asterisk-sound,core-,${lang}-${fmt},${suma}))
endif
EOF
cat <<EOF >> make_build
\$(eval \$(call BuildasteriskCoreSound,${lang}-${fmt},${lang} core sound Files. ${fmt} format,${fmt},core-${lang}))
\$(eval \$(call BuildasteriskVoicemail,voicemail-${lang}-${fmt},${lang} core voice mail Files. ${fmt} format,${fmt},core-${lang}))
EOF
cat <<EOF >> make_prepare
ifneq (\$(CONFIG_PACKAGE_asterisk-core-sounds-${lang}-${fmt}-digium)\$(CONFIG_PACKAGE_asterisk-core-sounds-voicemail-${lang}-${fmt}-digium),)
	\$(INSTALL_DIR) \$(PKG_BUILD_DIR)/core-${lang}
	\$(HOST_TAR) -C \$(PKG_BUILD_DIR)/core-${lang} -xzf \$(DL_DIR)/asterisk-core-sounds-${lang}-${fmt}-current.tar.gz
endif
EOF
done
done

for lang in en en_GB fr; do
for fmt in alaw g722 g729 gsm sln16 ulaw wav siren7 siren14; do
echo "${lang} ${fmt}"
if [ ! -f tmp/asterisk-extra-sounds-${lang}-${fmt}-current.tar.gz ];then wget -P tmp https://downloads.asterisk.org/pub/telephony/sounds/asterisk-extra-sounds-${lang}-${fmt}-current.tar.gz;fi
suma=$(sha256sum tmp/asterisk-extra-sounds-${lang}-${fmt}-current.tar.gz | cut -d" " -f1)
cat <<EOF >> make_download
ifneq (\$(CONFIG_PACKAGE_asterisk-extra-sounds-${lang}-${fmt}-digium),)
\$(eval \$(call Download,asterisk-sound,extra-,${lang}-${fmt},${suma}))
endif
EOF
if [ "${lang}" == "en_GB" ];then
cat <<EOF >> make_build
\$(eval \$(call BuildasteriskExtraLiteSound,${lang}-${fmt},${lang} extra sound Files. ${fmt} format,${fmt},extra-${lang}))
EOF
else
cat <<EOF >> make_build
\$(eval \$(call BuildasteriskExtraSound,${lang}-${fmt},${lang} extra sound Files. ${fmt} format,${fmt},extra-${lang}))
EOF
fi
cat <<EOF >> make_prepare
ifneq (\$(CONFIG_PACKAGE_asterisk-extra-sounds-${lang}-${fmt}-digium),)
	\$(INSTALL_DIR) \$(PKG_BUILD_DIR)/extra-${lang}
	\$(HOST_TAR) -C \$(PKG_BUILD_DIR)/extra-${lang} -xzf \$(DL_DIR)/asterisk-extra-sounds-${lang}-${fmt}-current.tar.gz
endif
EOF
done
done

for fmt in alaw g722 g729 gsm sln16 ulaw wav siren7 siren14; do
echo "${fmt}"
if [ ! -f tmp/asterisk-moh-opsound-${fmt}-current.tar.gz ];then wget -P tmp https://downloads.asterisk.org/pub/telephony/sounds/asterisk-moh-opsound-${fmt}-current.tar.gz;fi
suma=$(sha256sum tmp/asterisk-moh-opsound-${fmt}-current.tar.gz | cut -d" " -f1)
cat <<EOF >> make_download
ifneq (\$(CONFIG_PACKAGE_asterisk-moh-opsounds-${fmt}-digium),)
\$(eval \$(call Download,asterisk-moh,${fmt},${suma}))
endif
EOF
cat <<EOF >> make_build
\$(eval \$(call BuildasteriskMohSound,${fmt},moh sound Files. ${fmt} format))
EOF
cat <<EOF >> make_prepare
ifneq (\$(CONFIG_PACKAGE_asterisk-moh-opsounds-${fmt}-digium),)
	\$(INSTALL_DIR) \$(PKG_BUILD_DIR)/moh
	\$(HOST_TAR) -C \$(PKG_BUILD_DIR)/moh -xzf \$(DL_DIR)/asterisk-moh-opsound-${fmt}-current.tar.gz
endif
EOF
done

cat Makefile.stage1 > Makefile
cat make_download >> Makefile
cat Makefile.stage2 >> Makefile
cat make_prepare >> Makefile
cat Makefile.stage3 >> Makefile
cat make_build >> Makefile
sed -i "s/@VERSION@/${VERSION}/g" Makefile
